version: '3.8'

services:
  # OAuth Proxy Service
  oauth-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nintendo-oauth-proxy
    restart: unless-stopped
    ports:
      - "${OAUTH_PORT:-3000}:3000"
    environment:
      # Twitch OAuth
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}

      # YouTube OAuth
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}

      # Discord OAuth
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}

      # Twitter OAuth
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}

      # Instagram OAuth
      - INSTAGRAM_CLIENT_ID=${INSTAGRAM_CLIENT_ID}
      - INSTAGRAM_CLIENT_SECRET=${INSTAGRAM_CLIENT_SECRET}

      # TikTok OAuth
      - TIKTOK_CLIENT_KEY=${TIKTOK_CLIENT_KEY}
      - TIKTOK_CLIENT_SECRET=${TIKTOK_CLIENT_SECRET}

      # Service configuration
      - NODE_ENV=production
      - OAUTH_PORT=3000
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-https://nintendoemulator.app}
    command: ["node", "oauth-proxy.js"]
    networks:
      - nintendo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Authentication Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nintendo-auth-service
    restart: unless-stopped
    ports:
      - "${AUTH_PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - AUTH_PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-https://nintendoemulator.app}
    command: ["node", "auth-service.js"]
    networks:
      - nintendo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: nintendo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - oauth-proxy
      - auth-service
    networks:
      - nintendo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nintendo-network:
    driver: bridge

volumes:
  nginx-logs: